name: test workflow
on: 
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello-world
        run: echo "hello world"
        shell: pwsh

      - name: setup-node
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          run: node -v
      
      - name: node-version
        run: node -v
        shell: bash
